#!/bin/bash

#harus lakukan chmod +x di file install sebelumnya

termux-setup-storage
clear
echo "Press any key to continue.."
read -n 1 -s
mkdir -pv storage/shared/Linux\ Download\ Files
mkdir -pv storage/shared/WPS\ Backup
mkdir -pv /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/halo
chmod 777 -R /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs

cd
clear
echo "Copy instalation files.."
echo " "
pv storage/downloads/Paket1HD.tar > /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/Paket1HD.tar

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/

tar xvf Paket1HD.tar

rm Paket1HD.tar
