#!/bin/bash

notify-send -t 5000 "Update akan tersedia ⚠️"

sleep 3

notify-send -t 5000 "⚠️ Update fungsi print, open file langsung dan fix audio akan datang di minggu ini ⚠️"

sleep 3

notify-send -t 5000 "Versi ini tidak akan mendapatkan update setelah update ini."